In [4]:
import numpy as np

In [6]:
np.linspace(0.0, 1.0, num=11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [28]:
N = 11
x = np.linspace(0, 1, N, endpoint=True)

In [29]:
x

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [16]:
data = [0.72, 0.83, 0.3]

In [5]:
def create_bins(width, q):


    bins = []
    for low in np.arange(0.0, 0.0+ q*width, width):
        bins.append((low, low+width))
    return bins

In [6]:
bins = create_bins(width=0.1,q=10)

bins

[(0.0, 0.1),
 (0.1, 0.2),
 (0.2, 0.30000000000000004),
 (0.30000000000000004, 0.4),
 (0.4, 0.5),
 (0.5, 0.6),
 (0.6000000000000001, 0.7000000000000001),
 (0.7000000000000001, 0.8),
 (0.8, 0.9),
 (0.9, 1.0)]

In [54]:
 np.arange(0.1, 1,5 )

array([0.1])

In [1]:
def make_bins(data, bin_size):
  
  binned_data = {}  #variable to store the output
  bin_low = 0.0  #initial lower limit of the bin
  bin_high = bin_size  #initial high limit of the bin
  key = str(bin_low) + '-' + str(bin_high)  #variable stores the key name
  i = 1  #counter for the values of the floats fits in the actal bin
    
  for data_piece in data:  #iter over the sorted data
 
    while data_piece < bin_low:
      bin_low += bin_size
      bin_high += bin_size
  
    if bin_low <= data_piece < bin_high:  #if the current data fits the bin, lower inclusive and upper exclusive
      binned_data[key] = i  #append the counter for the key
      i += 1  #increment the key
  
    else:  # if the current data doesn't fit the bin
      i = 1  #reset counter to 1
      bin_low += bin_size
      bin_high += bin_size  #and increment the bin limits by the bin size
      key = str(bin_low) + '-' + str(bin_high) # generate a new key
      binned_data[key] = i  #and append it 
  
  return(binned_data)

In [ ]:
make_bins()