In [1]:
import numpy as np

In [2]:
data = open("data.txt","r")

In [3]:
lines = data.readlines()
dataused = lines[3:]

In [4]:
new_data = [x[:-1] for x in dataused]


In [5]:
arr = np.array(new_data)

In [6]:

data = arr.astype(np.float)

In [46]:
n = 5
sample = [data[k:k+n] for k in range(0, len(new_data), n)]

In [47]:
sample

[array([0.447033 , 0.5834817, 0.4770382, 0.5768076, 0.5283699]),
 array([0.5455481, 0.6858003, 0.4429366, 0.5334311, 0.5294322]),
 array([0.4705478, 0.5853158, 0.5714579, 0.4189266, 0.4701789]),
 array([0.4869248, 0.3751484, 0.497474 , 0.5530716, 0.4887033]),
 array([0.5613984, 0.563814 , 0.5091663, 0.5785368, 0.5156422]),
 array([0.50941  , 0.4893338, 0.6327241, 0.4197467, 0.6479772]),
 array([0.4293585, 0.6199369, 0.4945588, 0.7329152, 0.4517257]),
 array([0.5778234, 0.4969758, 0.5619396, 0.6520904, 0.5583883]),
 array([0.4359861, 0.4447215, 0.5224874, 0.4194073, 0.5677163]),
 array([0.4261581, 0.638685 , 0.5848516, 0.5318756, 0.6097636]),
 array([0.4483493, 0.4893985, 0.5103332, 0.4971617, 0.5302774]),
 array([0.5931727, 0.458582 , 0.5835312, 0.4612458, 0.4659913]),
 array([0.5110105, 0.3189472, 0.5369843, 0.6077548, 0.5498153]),
 array([0.5796511, 0.4341233, 0.3470951, 0.5597336, 0.5426913]),
 array([0.5548505, 0.4288907, 0.7160522, 0.6101507, 0.4764828]),
 array([0.6352757, 0.5837

In [8]:
import pandas as pd

In [9]:
ser = pd.Series(data)

In [10]:
sample_mean = ser.groupby(ser.index//5).mean()

In [11]:
sample_df = pd.DataFrame(sample)

In [12]:
sample_df.rename(columns = {0:'sample_1', 1:'sample_2', 2:'sample_3', 3:'sample_4', 4:'sample_5', }, inplace = True) 

In [13]:
sample_mean_df = pd.DataFrame(sample_mean)

In [14]:
sample_mean_df.rename(columns = {0:'sample_mean'  }, inplace = True) 

In [15]:
pd.concat([sample_df, sample_mean_df], axis=1)

sample_1  sample_2  sample_3  sample_4  sample_5  sample_mean
0      0.447033  0.583482  0.477038  0.576808  0.528370     0.522546
1      0.545548  0.685800  0.442937  0.533431  0.529432     0.547430
2      0.470548  0.585316  0.571458  0.418927  0.470179     0.503285
3      0.486925  0.375148  0.497474  0.553072  0.488703     0.480264
4      0.561398  0.563814  0.509166  0.578537  0.515642     0.545712
...         ...       ...       ...       ...       ...          ...
19995  0.625198  0.407890  0.547911  0.492213  0.479616     0.510566
19996  0.477059  0.303361  0.518820  0.347662  0.377563     0.404893
19997  0.422774  0.492952  0.607991  0.287632  0.554446     0.473159
19998  0.475346  0.449986  0.425173  0.417910  0.536878     0.461059
19999  0.398388  0.424605  0.722606  0.254769  0.508099     0.461693

[20000 rows x 6 columns]

In [16]:
delta = 0.1

In [17]:
binsize = (1.0-0.0)/0.1
binsize

10.0

In [18]:
bins = [(0.0,0.1), (0.1,0.2), (0.2,0.3), (0.3,0.4),(0.4,0.5),(0.5,0.6),(0.6,0.7), (0.7,0.8),(0.8,0.9),(0.9,1.0)]

In [19]:
bins2 = pd.IntervalIndex.from_tuples(bins)

In [20]:
categorical_object = pd.cut(sample_mean, bins2)


In [21]:
count = pd.value_counts(categorical_object)

In [22]:
count_df = pd.DataFrame(count)

In [23]:
count_df.rename(columns = {0:'#_of_samples'}, inplace = True) 

In [24]:
pmf = count_df["#_of_samples"]/(9758+9701+274+267)

In [25]:
pmf = pd.DataFrame(pmf)

In [26]:
pmf.rename(columns = {'#_of_samples':'PMF'}, inplace = True) 

In [27]:
pd.concat([count_df, pmf], axis=1)

#_of_samples      PMF
(0.4, 0.5]          9758  0.48790
(0.5, 0.6]          9701  0.48505
(0.6, 0.7]           274  0.01370
(0.3, 0.4]           267  0.01335
(0.0, 0.1]             0  0.00000
(0.1, 0.2]             0  0.00000
(0.2, 0.3]             0  0.00000
(0.7, 0.8]             0  0.00000
(0.8, 0.9]             0  0.00000
(0.9, 1.0]             0  0.00000

In [52]:
sample_mean

0        0.522546
1        0.547430
2        0.503285
3        0.480264
4        0.545712
           ...   
19995    0.510566
19996    0.404893
19997    0.473159
19998    0.461059
19999    0.461693
Length: 20000, dtype: float64

In [69]:
my_new_list = []
for x in sample_mean:
    if 0.3< x <= 0.4:
        x = x * 0.01335
        my_new_list.append(x) 
        
    elif 0.4<x<=0.5:
        x = x * 0.48790
        my_new_list.append(x) 
        
    elif 0.5<x<=0.6:
        x = x * 0.48505
        my_new_list.append(x)
        
    else:
        x = x * 0.01370
        my_new_list.append(x)

In [70]:
my_new_list

[0.2534609761039999,
 0.26553075658299996,
 0.24411858327,
 0.23432101051799997,
 0.26469738247700003,
 0.261848596518,
 0.264691309651,
 0.27620856967499996,
 0.233247288988,
 0.27078730163899994,
 0.24156125135800002,
 0.24859035622999998,
 0.24490291882099996,
 0.240368267552,
 0.270311273569,
 0.276379423687,
 0.20561436991199997,
 0.2621452725,
 0.236200411076,
 0.24449579695399998,
 0.226941161972,
 0.22242472046200001,
 0.25756526548299996,
 0.253331128219,
 0.238869955926,
 0.22852855438000005,
 0.25387262833799995,
 0.23673617406599998,
 0.008526421324000001,
 0.23784721018800004,
 0.264142640493,
 0.24406521806899997,
 0.26106857791200005,
 0.27391747480399997,
 0.26878551969099995,
 0.256405413923,
 0.25700255897800006,
 0.221518885322,
 0.24063786157599998,
 0.278008619328,
 0.277586616127,
 0.209291711244,
 0.261299655732,
 0.25938262172,
 0.24435241617399997,
 0.21540324422399998,
 0.008472223576,
 0.217346052266,
 0.23440780792799998,
 0.241190252198,
 0.2385797627640000

In [73]:
sum(my_new_list)/20000

0.23692471013231667

In [75]:
100000/5

20000.0

In [30]:
sum(data)/100000

0.5003089333150084

In [77]:
data * 0.55

array([0.24586815, 0.32091494, 0.26237101, ..., 0.39743319, 0.14012268,
       0.27945429])

In [31]:
import matplotlib.pyplot as plt

In [32]:
def create_bins(n, delta):
    quantity = 100000/n

    bins = []
    for low in np.arange(0.0, 0.0+ quantity*delta, delta):
        bins.append((low, low+delta))
    return bins